# ─────────────────────────────────────────────────────────────────────
#  「✦ HYPERPAPER CONFIG ✦ 」
# ─────────────────────────────────────────────────────────────────────

# ── WALLPAPER ────────────────────────────────────────────────────────
wallpaper {
    monitor =
    path = /home/adi/walls/wallpaperflare.com_wallpaper(1).jpg
}

# ── GENERAL ──────────────────────────────────────────────────────────
splash = false
ipc = on
